# Project information
site_name: Plotpp
site_author: Tobias Wallner
site_description: >-
    Plotting library for C++. Alows plotting into popup-windows as well as saveing them
    in a large variety of dataformats. Uses Gnuplot as a backend.

# Repo     
repo_name: TobiasWallner/plotpp
repo_url: https://github.com/TobiasWallner/plotpp


# Copyright
copyright: Copyright &copy; Tobias Wallner

nav:
    - Home: index.md
    - Plotting Styles: plotting_styles/index.md
    - API:
        - Overview: API/Namespaces/namespaceplotpp.md
        - Namespaces: API/Namespaces/index.md
        - Classes: API/Classes/index.md
        - Examples: API/Examples/index.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - content.action.edit
    - content.action.view
    - navigation.sections
    #- navigation.tabs # Uses tabs in the header instead of at the left of the page
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy  # Adds a "copy" button to code blocks
    - content.code.annotate
    
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower